export const HOST = 'http://localhost:';
export const GATEWAY_PORT = 40005;
export const SERVICE_NAME = '/employee-service';
export const ORIGIN = HOST + GATEWAY_PORT + SERVICE_NAME;

export const ENDPOINT_GET_LOGIN = ORIGIN + '/employee/login';
export const ENDPOINT_POST_PRODUCT = ORIGIN + '/product/create';
export const ENDPOINT_GET_PRODUCTS = ORIGIN + '/product/get_all';
export const ENDPOINT_POST_UNDERWRITE = ORIGIN + '/product/underwrite';
export const ENDPOINT_GET_BOARDS = ORIGIN + '/board/get_all';
export const ENDPOINT_POST_ANSWER_BOARD = ORIGIN + '/board/answer';
export const ENDPOINT_GET_MANAGING_CLAIMS = ORIGIN + '/claim/get_all_by_employee_id';
export const ENDPOINT_POST_REPORT = ORIGIN + '/claim/submit_report';
export const ENDPOINT_POST_REVIEW_CLAIM = ORIGIN + '/claim/review_claim';
export const ENDPOINT_GET_ACCEPTED_CLAIMS = ORIGIN + '/claim/get_accepted';
export const ENDPOINT_POST_PAY_COMPENSATION = ORIGIN + '/claim/pay_compensation';
export const ENDPOINT_GET_CUSTOMER_STATISTICS = ORIGIN + '/customer/get_statistics';
export const ENDPOINT_GET_CLAIM_STATISTICS = ORIGIN + '/claim/get_statistics';

// export const ENDPOINT_GET_LOGIN = 'http://localhost:40045/our_insurance/employee/login';
// export const ENDPOINT_POST_PRODUCT = 'http://localhost:40045/our_insurance/product';
// export const ENDPOINT_GET_PRODUCTS = 'http://localhost:40045/our_insurance/products';
// export const ENDPOINT_POST_UNDERWRITE = 'http://localhost:40045/our_insurance/product/underwrite'
// export const ENDPOINT_GET_BOARDS = 'http://localhost:40045/our_insurance/boards';
// export const ENDPOINT_POST_ANSWER_BOARD = 'http://localhost:40045/our_insurance/board/answer';
// export const ENDPOINT_GET_MANAGING_CLAIMS = 'http://localhost:40045/our_insurance/claims/managing';
// export const ENDPOINT_POST_REPORT = 'http://localhost:40045/our_insurance/claim/report';
// export const ENDPOINT_GET_ACCEPTED_CLAIMS = 'http://localhost:40045/our_insurance/claims/accepted';
// export const ENDPOINT_POST_PAY_COMPENSATION = 'http://localhost:40045/our_insurance/claim/pay_compensation';
// export const ENDPOINT_GET_CUSTOMER_STATISTICS = 'http://localhost:40045/our_insurance/customer/statistics';
// export const ENDPOINT_GET_CLAIM_STATISTICS = 'http://localhost:40045/our_insurance/claim/statistics';